version: '3.9'
services:

  postgres_ipr:
    image: postgres:14.2
    container_name: postgres_ipr
    environment:
      - POSTGRES_PASSWORD=ipr
    ports:
      - "5432:5432"
    volumes:
      - ipr_pgdata:/var/lib/postgresql/data
    networks:
      - ipr

  zk_ipr:
    image: wurstmeister/zookeeper
    hostname: zk_ipr
    networks:
      - ipr
    ports:
      - "2181:2181"

  kafka_ipr:
    image: wurstmeister/kafka
    hostname: kafka_ipr
    networks:
      - ipr
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka_ipr:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: zk_ipr:2181
    depends_on:
      - zk_ipr

  kafdrop_ipr:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop_ipr
    restart: "no"
    networks:
      - ipr
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka_ipr:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka_ipr

volumes:
  ipr_pgdata:
    driver: local

networks:
  ipr:
    name: ipr
    driver: bridge