CREATE TABLE some_table
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ipr_id  BIGINT REFERENCES ipr,
    field_1 VARCHAR(100),
    field_2 VARCHAR(100)
);

CREATE TABLE ipr
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message   VARCHAR(256),
    number    BIGINT,
    is_ok     BOOLEAN,
    some_date DATE,
    dual      VARCHAR(256)
);


INSERT INTO ipr (id, message, number, is_ok, some_date, dual)
VALUES (-1, 'TEXT1', 111, TRUE, '01-01-2021', 'WWW_176'),
       (-2, 'TEXT2', 222, FALSE, '02-02-2022', 'DDD_1');

INSERT INTO some_table (id, ipr_id, field_1, field_2)
VALUES (-11, -1, 'text1', 'text2'),
       (-12, -1, 'tex1', 'tex2'),
       (-13, -1, 'te1', 'te2'),
       (-14, -1, 't1', 't2'),
       (-21, -2, 'mess1', 'mess2'),
       (-22, -2, 'm1', 'm2');
